### ISSUE TITLE
Upgrade sharp version

### ISSUE THREAD

**Issue by sollidy** [Brakebein/node-three-gltf#10]
Please, can you upgrade version of `sharp` to latest (i tested v.0.33.3, work perfect), cause when i use your module inside node-worker, i got this error:
![Screenshot from 2024-04-17 23-11-48](https://github.com/Brakebein/node-three-gltf/assets/70297692/61b4c98e-054c-4bf7-a193-8bad745d91cc)

**Comment by Brakebein** [comment]
Merged and published with version 1.6.0.
